### Send POST request with json body
POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "SENIOR",
  "developerSkillType": "BACK_END",
  "experienceYear": 12,
  "memberId": "mini",
  "name": "mouse kim",
  "age": 32
}